source/DasBlog.Web.Core/DasBlog.Core.csproj
source/DasBlog.Web.Core/Services/Interfaces/ISiteRepairer.cs
source/DasBlog.Web.Core/Services/SiteRepairer.cs
source/DasBlog.Web.UI/Startup.cs

addresses: newly installed app throws exception at startup due to missing binary dir #114
@poppastring I suggest you prioritise this over PR #113 which I will then rebase.  We don't want any aspiring contributors to be discouraged by a breaking app - the worst sin.

Implemented SiteRepairer to handle minor site problems at startup

---

source/DasBlog.Web.Repositories/BlogManager.cs
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs

Logged errors that happen when attempting to edit or add a post. These were being swallowed and were not getting logged. This should remove the three warnings of unused Exception variables while firing the build, as described in issue #138 - @poppastring - please feel free to review and do let me know if any added changes are required.

Logged errors that happen when attempting to edit or add a post.  Issue #138.

---

source/DasBlog.Tests/FunctionalTests/IntegrationTests/PrototypeIntegrationTests.cs

It was/is my intention to give the functional/integration tests their own sandbox in terms of content and config directories which should prevent this nonsense recurring (test was relying on a specific user in the production config).  It's pretty much in the existing code.  I will activate it when I fix the users bugs or when I do some refactoring.

fixed broken test of users

---

source/DasBlog All.sln
source/newtelligence.DasBlog.Runtime/Test/newtelligence.DasBlog.runtime.Test.csproj

I'm not sure why this started happening on Surfface Pro 4/Windows 10 - dotnet build objected (but in any case we need to be case sensitive to simplify future move to posix).  No problem on IMac/Windows 10

broken build - windows 10 being picky about capitalisation

---

source/DasBlog.Tests/UnitTests/Services/BlogDataServiceTest.cs

BlogDataService_GetEntriesForDayMaxValue_Successful (renamed
BlogDataService_GetPublicEntriesForDayMaxValue_Successful) failed
because the expected count (26) included non-public entries
BlogDataService_GetEntriesWithFalse_Successful failed because the
latest deleted entry (created by a previous test)
was returned in the count of entries
Issue created: Last deleted blog post shows up in return from GetEntries() #176

Fixed 2 failing unit tests when run under "dotnet test"

---

source/DasBlog.Web.UI/Models/BlogViewModels/CategoryListViewModel.cs

@poppastring - The second part only exhibits the behaviour you describe above if you are logged in as an admin.
Try with a contributor / not logged in and you'll only see the one category listed. As an Admin it returns all items in the category and any other category that those posts may be added to.  This is probably desired behaviour.

Sorted category list alphabetically

---

source/DasBlog.Tests/FunctionalTests/DasBlog.Tests.FunctionalTests.csproj
source/DasBlog.Tests/UnitTests/DasBlog.Tests.UnitTests.csproj
source/DasBlog.Web.UI/DasBlog.Web.csproj

As per the [official migratrion guide](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.2#update-the-project-file-to-use-21-versions), this package should not be versioned.
This should also fix issue #214.

Remove version reference for Microsoft.AspNetCore.App package

---

source/DasBlog.Web.UI/Settings/DasBlogLocationExpander.cs

I need to OVERRIDE _commentPartial and other views, but the theme is added to the end. If you add it to the BEGINNING then themes can optionally override things just by making a file with the same name. This is a cleaner fallback (test your site) so I can add a _CommentBlockPartial inside my theme folder AND not edit the /Views/Shared files!

Add the theme folder FIRST so themes can be overridden

---

source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Models/BlogViewModels/ListCommentsViewModel.cs
source/DasBlog.Web.UI/Views/Shared/_CommentBlockPartial.cshtml

Wanted to ensure the default behavior would redirect GUID based URLs to the title based URLs.

Fixing default comment links behavior

---

source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Controllers/FeedController.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs

Removing "post" from the comment links URI.
Added endpoints for trackback/pingbacks (although they do nothing).

Remove "post" from comments URL

---

source/DasBlog.Web.UI/Controllers/HomeController.cs

Uses the existing site config value EnableStartPageCaching.
Enabled by default

Support enable or disable home page caching

---

source/DasBlog.Web.UI/AutomapperExtensions.cs

This fix reduces the the list of assemblies to focus on types found in dasblog assemblies only.
Not sure why this exception suddenly starting appearing.
Cannot replicate locally.

Exceptions were being thrown from he assembly scan. 

---

source/DasBlog.Web.UI/Controllers/FeedController.cs

Starting with ASP.NET Core 3.0, synchronous server operations are disabled by default.

Posting a blogs fails, this should resolve it.

---

source/DasBlog.Web.Repositories/BlogManager.cs

My latest changes attempted to send an alert email even if we were not configured to do so. This is the fix.

Only send an email if configured.

---

source/DasBlog.Web.UI/TagHelpers/TitleLinkTagHelper.cs

Fixed default name of the Title TagHelper to title rather than the permalink.

Another TagHelper fix

---

source/DasBlog.Services/FileManagement/ConfigFilePathsDataOption.cs
source/DasBlog.Web.Repositories/FileSystemBinaryManager.cs
source/DasBlog.Web.Repositories/XmlRpcManager.cs
source/DasBlog.Web.UI/Startup.cs
source/newtelligence.DasBlog.Runtime/FileSystemBinaryDataService.cs

By default images are always placed in a "binary" folder which is now always placed as a subdirectory of the content folder. (previously defined in an used setting).
Fixed static folder for serving images (I broke this yesterday).
Fixed uploading of images via live writer and the create/post url (I broke this yesterday).
I really need a comprehensive integration testing framework to avoid dumb mistakes.

Fixing image/binary folder issues

---

source/DasBlog.Web.UI/Program.cs
source/DasBlog.Web.UI/Startup.cs

This fix ensures that if an environment name is not defined we default to standard config files. 
Additional  usage of path combine to help xplat

config file resiliency

---

source/DasBlog.Services/Site/SiteRepairer.cs
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/Startup.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

We are, correctly, back to using **BinariesDir**
Changed the default value to "content/binary" (was "~/content/binary"). If you have the old value you will be fine.
**BinariesDir** is modifiable via the settings page
We create the binaries folder on startup if it does not already exist (I broke this in the last build).
I use the DirectoryInfo object to ensure we have consistent file path to the binaries folder (which should also be more consistent for Linux).

Binaries folder fixes

---

source/DasBlog.Web.UI/TagHelpers/Site/SitePageControlTagHelper.cs

Replaced the setting of PostCount and PageNumber with a try catch block, which was catching for nulls, to using the null-coalescing operator by way of casting to nullable ints.
(I know this wasn't an Issue, but it was one of those things that popped up when I first started to debug some things.  Thought the change would make debugging less annoying, what with VS breaking if you have the break on exceptions set.)

Remove the NullException catch from the ProcessAsync method.

---

source/DasBlog.Tests/UnitTests/Services/EntryCollectionTest.cs
source/DasBlog.Web.Repositories/XmlRpcManager.cs

Needed a HtmllDecode for the title when defining the title before saving to file.
This did not impact the Web UI based posting.

Fixing Open Live Write Titles with apostrophe

---

source/DasBlog.Tests/DasBlog.Test.Integration/SeleniumPageTests.cs

This was creating a minor annoying warning while firing a build about an unused variable and was causing vs code to highlight the issue. Basically removed the unused exception variable to get rid of the warning.

Removed Unused Exception Variable ex.

---

source/DasBlog.Services/Site/SiteRepairer.cs

Fix to ensure that "content/radioStories" folder exists before creating a static folder reference in the startup page..

content folder fix

---

azure-pipelines.yml
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Controllers/DasBlogBaseController.cs

When very old links come in like 
`https://www.hanselman.com/blog/PermaLink.aspx?guid=b5790285-2eb7-4198-ac1d-6cfbf20735a4
`
and you have an a redirect in IISExpress.xml like this:
```
<rule name="Very old perm;alink style (guid)" stopProcessing="true">
<match url="^PermaLink.aspx" />
<conditions>
<add input="{QUERY_STRING}" pattern="&amp;?guid=(.*)" />
</conditions>
<action type="Redirect" url="/blog/post/{C:1}" redirectType="Permanent" />
</rule>
```
You'll end up on 
```
http://hanselman.com/blog/post/b5790285-2eb7-4198-ac1d-6cfbf20735a4
```
and get a null error because comments aren't loaded (see the DasBlogBaseController) so this fixes the null check, but the larger issue of "302 redirect to the canonical URL" remains, but I got lost in BlogPostController.

comments aren't loaded, null check for /post/guid URLs

---

source/DasBlog.Tests/UnitTests/UI/TagHelperTest.cs
source/DasBlog.Web.UI/TagHelpers/Post/PostCommentLinkTagHelper.cs

Removed line from PostCommentLinkTagHelper that added the ID attribute
Modified unit test to check ID attribute was not present

remove id attribute from PostCommentLink TagHelper

---

source/DasBlog.Tests/UnitTests/UI/PostToFacebookTagHelperTest.cs
source/DasBlog.Web.UI/TagHelpers/Post/PostToFacebookTagHelper.cs

Fixed href formatting to use Uri and UrlEncoder classes
Added unit tests
Fixes poppastring/dasblog-core#451

fix facebook tag helper to use more robust mechanism for href formatting

---

source/DasBlog.Web.UI/Startup.cs

Needed to reduced the number of settings that relied on a complete restart. This may help.

Remove values from the Startp.Startup() method.

---

azure-pipelines.yml

Fixes poppastring/dasblog-core#459
- Use variable for major.minor version string
- Only use Major.Minor versioning for Main branch builds
- Use ProjectName for artifact prefix
- Add additional build step to control of zip filename
- Publish only Windows build
- Publishing both Windows and Linux will cause an Artifact name clash
Draft releases have been deprecated in Azure DevOps
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops#what-is-a-draft-release
You need to modify you Release pipeline to manage release types.

Name build output artifacts based on variables

---

source/newtelligence.DasBlog.Runtime/BlogDataService.cs

since it is not used, and it is obsolete in core

remove TimeZone param from InternalGetDayEntries

---

azure-pipelines.yml
source/DasBlog.Web.UI/Startup.cs

This allows you to startup immediately following deployment in a "Production" (or Staging, etc.) environment without having to manual create the environment config files.
site.[Environment].config, meta.[Environment].Config,  and appSettings.[Environment].Config become optional files [`in ConfigurationBuilder()..AddXmlFile()`], So if they are missing you will not fail, login and save settings will create new files.
siteSecurity.[Environment].Config and IISUrlRewrite.[Environment].Config are now created as part of the start up checks.
This will not impact existing deployments.

Fault tolerant startup for Production/Staging

---

azure-pipelines.yml

Fixed #512
- disable dotnet publish task from creating zip file
- specify specific folder to add to zip file
- exclude root folder from zip file
- update archiveFile name to remove `imageName`
- update publish targetPath to remove `imageName`

Fix zip output to remove unnecessary folders

---

source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Themes/dasblog/_Layout.cshtml
source/DasBlog.Web.UI/Views/Account/Login.cshtml
source/DasBlog.Web.UI/Views/Account/Register.cshtml
source/DasBlog.Web.UI/Views/Activity/ActivityList.cshtml
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml
source/DasBlog.Web.UI/Views/BlogPost/CreatePost.cshtml
source/DasBlog.Web.UI/Views/BlogPost/EditPost.cshtml
source/DasBlog.Web.UI/Views/Users/ViewEditUser.cshtml

When you access admin pages it shows pages with the "dasblog" themes.
Theme designers no longer have to worry about those pages (unless they want to).

Admin theme pages

---

source/DasBlog.Services/ConfigFile/Interfaces/ISiteConfig.cs
source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml
source/DasBlog.Web.UI/Views/Home/About.cshtml

Added a site setting to allow the About view to be enabled, default is disabled and returns NoContent.
Using the default ViewData["PageTitle"] for the title and the tag helpers for site-sub-title and site-description for the content.

Added the ability to use the Home/About page

---

source/DasBlog.Web.UI/TagHelpers/Comments/CommentUserHomePageLink.cs

Updated so that the anchor turns into a span if commenter does not leave a home page reference.

Home page Comment link 

---

source/DasBlog.Web.UI/Models/BlogViewModels/PostViewModel.cs

Changed it to a MinLength attribute, to maintain that validation check from the original.

Removed max length validation on blog post title

---

source/DasBlog.Web.UI/wwwroot/css/site.css

Rather than just making all images in content marked with the dbc-post-content class 100% height and width, change that style to a class of its own.

Changed img size rule to require a specific class name

---

source/DasBlog.Web.UI/Mappers/ProfilePost.cs

As a post does not have to have a category set, check the string is not null before splitting it.

Check category string is not null before splitting

---

source/DasBlog.Web.UI/TagHelpers/Post/PostContentTagHelper.cs

as this appears to be breaking correctly encoded entries especially when trying to demonstrate HTML, XML, etc..

Removing the additional HTML Decode 

---

azure-pipelines.yml
source/DasBlog.CLI/DasBlog.CLI.csproj
source/DasBlog.Services/ConfigFile/Interfaces/ISiteConfig.cs
source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Services/DasBlog.Services.csproj
source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Web.Core/DasBlog.Core.csproj
source/DasBlog.Web.Repositories/DasBlog.Managers.csproj
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/TagHelpers/Post/PostContentTagHelper.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml
source/newtelligence.DasBlog.Runtime/newtelligence.DasBlog.Runtime.csproj

Add a setting to allow for Double Decoding the content of a blog post.
It is false by default, meaning, if you want to double decode you need to configure it in the admin page.

Configure Double Decoding

---

source/newtelligence.DasBlog.Runtime/Entry.cs

Publishing from OLW without ay categories set for the post causes an exception to be thrown, as the code just attempts to trim a possible trailing semi-colon from a null object.
Added check so only trim the value if it is a valid string.

Check categories value before trimming it

---

azure-pipelines.yml
source/DasBlog.Services/ConfigFile/Interfaces/ISiteConfig.cs
source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Services/DasBlog.Services.csproj
source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/TagHelpers/Post/PostContentTagHelper.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

We will always Double Decode to account for the code we place in the `<pre>` tag.

Rolling back the option to double decode. 

---

azure-pipelines.yml
source/DasBlog.Services/ConfigFile/Interfaces/ISiteConfig.cs
source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Services/DasBlog.Services.csproj
source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Web.Repositories/BlogManager.cs
source/DasBlog.Web.Repositories/DasBlog.Managers.csproj
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

Added a new SMTP setting for the from email address to use when sending an email.  This new setting will allow support for email services like SendGrid that does not use a valid email address for the SMTP user name  If this new setting is null or blank then the email Send user name setting will be used for the from email address to maintain backward compatibility with existing blogs.
This fixes #526

Added setting for from email address

---

source/DasBlog.Tests/UnitTests/UI/CommentContentTagHelperTest.cs
source/DasBlog.Web.UI/TagHelpers/Comments/CommentContentTagHelper.cs

This PR addresses an issue in the comment content tag helper where an exception is thrown when the comment text is null
[Issue 601](https://github.com/poppastring/dasblog-core/issues/601)

issue:#601:comment content tag helper throws null exception

---

source/DasBlog.CLI/Program.cs

This assumes that we are configuring DasBlog for a Production environment in the absence of the "ASPNETCORE_ENVIRONMENT" environment variable.

Resolves the issue of configuring DasBlog locally before uploading to a host

---

README.md
deploy/azuredeploy.json

This is the initial PR to start the process of adding a DEPLOY TO AZURE button to the documentation (#492)
This is a straightforward addition of a "deploy" folder off of the root of the repository, containing an ARM template for deploying DasBlogCore to an Azure App Service. There will be two follow-up PRs: 
- One to the Wiki pages to add the DTA button and instructions on how to configure it.
- One to update the main project README with the DTA button and a link to the deployment instructions in the Wiki.
This ARM template will allow the user to deploy a single App Service using:
- Windows
- 64-bit Process
- Git-Deployment
The user has the ability to change the following settings when deploying the template:
- Name of the application/site
- The name provided by the user will …

Issue 492 deploytoazurebutton

---

source/DasBlog.Web.Repositories/BlogManager.cs
source/DasBlog.Web.UI/Themes/median/_Layout.cshtml
source/DasBlog.Web.UI/Views/Shared/_BlogItems.cshtml
source/DasBlog.Web.UI/Views/Shared/_BlogItemsSummary.cshtml

Fix theme issues
Fix null reference issues

Fix a few bugs

---

source/DasBlog.Web.UI/Models/AdminViewModels/TwitterCardViewModel.cs

The name of the Twitter card with a large image is "summary_large_image". 
(Btw, it might make sense to allow for the card model to be picked per post)

Twitter Card Model Fix

---

source/DasBlog.Web.UI/Controllers/DasBlogBaseController.cs

* Description has an extra field but was always set to a shortened version of Content. 
* The image and video URLs must be absolute for inclusion in metadata fields. RelativeToRoot should pass already absolute URIs back as-is if given them.
I'm also adding a fewother items to View Data that I found useful to have in the template.

Adding view data to base controller and fixing description

---

source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/TagHelpers/RichEdit/TinyMceBuilder.cs

There are a few fixes here for #665 
* TinyMCEBuilder must use absolute URIs for embeddings like images because the resulting page content "moves around" in the site hierarchy and the links break.
* Permalinks must be absolute. The "navigate to permalink" link in the editor broke.
* Local redirects must be relative to the site root
* Site config needs to fix up a root that doesn't end in a slash. That's the most fundamental issue.

Fixing issues occuring when dasBlog uses a subdir

---

source/DasBlog.Services/ConfigFile/Interfaces/ISiteConfig.cs
source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Web.Repositories/FileSystemBinaryManager.cs
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml
source/newtelligence.DasBlog.Runtime/CdnManager.cs
source/newtelligence.DasBlog.Runtime/FileSystemBinaryDataService.cs
source/newtelligence.DasBlog.Runtime/ICdnManager.cs

This approach adds code to dasblog-core along exactly the same vein as the present code base.
However it feels slightly overworked, as the actual business logic change, other than one more site.config setting, ultimately is one line of code.
The alternate approach would be to inline the code change in the constructor of the FileSystemBinaryManager and set the CDN domain in the binaryRoot field. Happy to do either.
As I see it this extends an easy CDN option for those that wish to host their blog with a CDN. I will also add this in detail to the wiki documentation.

Adding CDN support for binary content. Configurable from site.config.

---

source/DasBlog.Web.Repositories/ActivityPubManager.cs

Removed validation so that the blog can support its own Web finger and redirecting to another federated server

Fixed for WebFinger account validation

---

source/DasBlog.Web.Repositories/BlogManager.cs
source/DasBlog.Web.Repositories/Interfaces/IBlogManager.cs
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Mappers/ProfileSaticPages.cs
source/DasBlog.Web.UI/Models/BlogViewModels/StaticPageViewModel.cs
source/DasBlog.Web.UI/Startup.cs
source/DasBlog.Web.UI/Views/BlogPost/LoadStaticPage.cshtml
source/newtelligence.DasBlog.Runtime/BlogDataService.cs
source/newtelligence.DasBlog.Runtime/IBlogDataService.cs
source/newtelligence.DasBlog.Runtime/StaticPage.cs

This is the basic implementation as discussed in #686.
Once the merge is done testing is really simple. 
1. In your content folder, create a folder called "static" inside your content folder (wherever that is configured). e.g.
2. Inside the static folder keep a ".html" file with simple HTML:
3. It can hold any static HTML:
4. Save the File, run the blog, and now replace ".html" either with ".aspx" or nothing (depending on your blog's routing scheme):
5.  Of course if you are using aspx based URL scheme (older migrations of historic blogs with URLs retained) you can also retain the URL of your static page and use ".aspx" in the end:
Once this PR is approved I will be working on:
1. Test Cases.
2. Caching (this would be better than reading from the file) - in the long run, we should do …

First implementation of static pages as per #686.

---

source/DasBlog.Services/Site/SiteHttpContext.cs
source/DasBlog.Web.Repositories/FileSystemBinaryManager.cs
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs
source/DasBlog.Web.UI/Startup.cs
source/DasBlog.Web.UI/TagHelpers/Post/PostToFacebookTagHelper.cs
source/DasBlog.Web.UI/TagHelpers/Post/PostToLinkedInTagHelper.cs
source/DasBlog.Web.UI/TagHelpers/Post/PostToRedditTagHelper.cs
source/DasBlog.Web.UI/TagHelpers/Post/PostToTwitterTagHelper.cs

The assumption is that upon first deployment the site will start up without a root URL defined.
dasblog will allow you to login and change the root url through the web page and update the root URL.
Some functions will still not work so this should still be the first thing you do.

Simplify the site initialization process

---

source/DasBlog All.sln
source/DasBlog.CLI/DasBlog.CLI.csproj
source/DasBlog.Services/DasBlog.Services.csproj
source/DasBlog.Tests/DasBlog.Test.Integration/DasBlog.Test.Integration.csproj
source/DasBlog.Tests/UnitTests/DasBlog.Tests.UnitTests.csproj
source/DasBlog.Web.Core/DasBlog.Core.csproj
source/DasBlog.Web.Repositories/DasBlog.Managers.csproj
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/Directory.Packages.props
source/newtelligence.DasBlog.Runtime/newtelligence.DasBlog.Runtime.csproj

Add a Directory.Package.props file to enable central package management.
This has two advantages:
- Changes to NuGet package versions only needs to be done in one central file (.csproj files are unchanged for future NuGet version updates)
- All projects use the same NuGet package version.
The NuGet package versions itself are not changed in this PR to keep the scope limited to the introduction of a Directory.Packages.props file. This is a first step to resolve #704.

Enable central NuGet package version management

---

source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

Using type="number" will ensure that the decimal symbol is always a dot, which will prevent that the validation will fail when the server is running on a non en-us configuration. The HTML input element type="number" also display a spinner, The default step size is 1, changed it to .1 to make the spinner useful.
Remark 1: the input element number also provides min/max settings to limit the user input. A custom HtmlHelperExtensions would be needed however to extract the range values from the model to set these values. Adding min/max manuallly in the .cshtml file is also possible but would duplicate the configuration SiteViewModel. Client validation will also ensure the range, so no functionality is lost.
Remark 2: an alternative would be change the page to use ASP.NET Tag Helpers (asp-for), …

Change RecaptchaMinimumScore from input text to number to solve #706

---

source/DasBlog.Web.Core/Extensions/StringExtensions.cs

Enhance StripHtml method in StringExtensions.cs
Updated the `StripHtml` method to replace closing paragraph
tags and `<br>` tags with a space, while preserving the
functionality of removing all other HTML tags.

Enhance StripHtml method in StringExtensions.cs

---

source/DasBlog.Web.UI/Controllers/AdminController.cs
source/DasBlog.Web.UI/Models/AdminViewModels/BlogPostListViewModel.cs

Avoiding a stackoverflow exception by using the View rather than the return the same method.
Resolves #706

Avoiding a stackoverflow exception

---

source/DasBlog.Web.UI/TagHelpers/Post/PostToBlueSkyTagHelper.cs
source/DasBlog.Web.UI/Themes/darkly/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/dasblog/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/journal/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/median/_BlogItem.cshtml

Add BlueSky sharing support to blog posts
Added BlueSky as a new social media sharing option in `_BlogItem.cshtml`, alongside Twitter, Reddit, Facebook, and LinkedIn.
Introduced `PostToBlueSkyTagHelper` to generate BlueSky sharing links, including post title and permalink encoding. Updated Razor views to ensure consistent integration of the BlueSky sharing feature across all relevant sections of the blog post footer.

Add BlueSky sharing support to blog posts

---

source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Models/AdminViewModels/BlogPostListViewModel.cs
source/DasBlog.Web.UI/Models/AdminViewModels/CategoryListViewModel.cs
source/DasBlog.Web.UI/Views/Account/Login.cshtml
source/DasBlog.Web.UI/Views/Shared/_Admin_BlogEditing.cshtml
source/DasBlog.Web.UI/Views/Shared/_Admin_Comments.cshtml
source/DasBlog.Web.UI/Views/Shared/_Admin_FrontPage.cshtml
source/DasBlog.Web.UI/Views/Shared/_Admin_Internal.cshtml
source/DasBlog.Web.UI/Views/Shared/_Admin_RSSFeed.cshtml
source/DasBlog.Web.UI/Views/Shared/_CommentAddPartial.cshtml

New feature and user interface improvements.
This pull request introduces new configuration options and enhances the user interface across several files for better usability and functionality. Key changes include:
- `site.Development.config` and `site.config`: Added settings for `PostPinnedToHomePage` and `AlwaysIncludeContentInRSS`.
- `CategoryListViewModel.cs`: Introduced a new class for managing categories with an initialization method.
- `Login.cshtml`: Improved layout and added validation feedback.
- `_Admin_FrontPage.cshtml`: Replaced text box for front page category selection with a dropdown list.
- `_Admin_BlogEditing.cshtml` and `_Admin_Comments.cshtml`: Added scripts to manage form element states based on user interactions.
Close #720

Improve the admin mechanics

---

source/DasBlog.Web.Core/Common/Utils.cs
source/DasBlog.Web.Repositories/SiteSecurityManager.cs

Code cleanup and modernization of cryptographic method usage.
This pull request updates cryptographic method instantiations to use modern factory methods and removes redundant code.
- `Utils.cs`: Replaced `MD5CryptoServiceProvider` with `MD5.Create()` in `GetGravatarHash`.
- `SiteSecurityManager.cs`: Removed duplicate `using` directive and replaced `SHA512Managed.Create()` with `SHA512.Create()` and `MD5CryptoServiceProvider.Create()` with `MD5.Create()` in relevant methods.
Closes #724 #723

Cryptographic method cleanup
