README.md

Had a few inquiries about progress thought I would add it to the read me.

Update in ReadMe with progress info

---

source/DasBlog All.sln
source/DasBlog.Tests/Config/metaConfig.xml
source/DasBlog.Tests/Config/site.config
source/DasBlog.Tests/Config/siteSecurity.config
source/DasBlog.Tests/DasBlog.Tests.csproj
source/DasBlog.Tests/HostingEnvironmentTest.cs
source/DasBlog.Tests/Properties/launchSettings.json
source/DasBlog.Tests/Repositories/SiteSecurityRepository_Test.cs
source/DasBlog.Tests/UI/TagHelper_Test.cs
source/DasBlog.Tests/appsettings.json
source/DasBlog.Web.UI/Startup.cs

Stubbed in the test project

---

source/DasBlog.Web.UI/Controllers/HomeController.cs
source/DasBlog.Web.UI/Models/BlogViewModels/PostViewModel.cs
source/DasBlog.Web.UI/PostCreatedTagHelper.cs
source/DasBlog.Web.UI/Themes/DasBlog/_PostPartial.cshtml
source/DasBlog.Web.UI/Themes/_ViewImports.cshtml

- Added Post date created - TagHelper as per following blog post https://www.poppastring.com/blog/CreatingTagHelpersWithCoreMVC.aspx
- As per discussion, created the tag-helper class in UI project rather than creating the separate folder for 'TagHelper'.
- Once #25 is resolved, will add Unit Tests for this TagHelper class.
- This resolves #5

Added Post date created - TagHelper

---

source/DasBlog.Web.Core/IDasBlogSettings.cs
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Controllers/AccountController.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs
source/DasBlog.Web.UI/DasBlog.Web.UI.csproj
source/DasBlog.Web.UI/Helpers/CategoriesListTagHelper.cs
source/DasBlog.Web.UI/Helpers/TitleLinkTagHelper.cs
source/DasBlog.Web.UI/Mappers/ProfilePost.cs
source/DasBlog.Web.UI/Models/BlogViewModels/CategoryViewModel.cs
source/DasBlog.Web.UI/Models/BlogViewModels/PostViewModel.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs
source/DasBlog.Web.UI/Startup.cs
source/DasBlog.Web.UI/Themes/DasBlog/_LoginPartial.cshtml
source/DasBlog.Web.UI/Themes/DasBlog/_PostPartial.cshtml
source/newtelligence.DasBlog.Runtime/Entry.cs
source/newtelligence.DasBlog.Util/HttpHelper.cs

Closes #17 
Closes #8
Closes #4
Also introduced AutoMapper

Fixes for #17, #8, #4

---

source/DasBlog All.sln
source/DasBlog.Web.Core/Configuration/ISiteSecurityConfig.cs
source/DasBlog.Web.Core/Configuration/SiteSecurityConfig.cs
source/DasBlog.Web.Core/IDasBlogSettings.cs
source/DasBlog.Web.Core/Security/Role.cs
source/DasBlog.Web.Core/Security/User.cs
source/DasBlog.Web.Repositories/Interfaces/ISiteSecurityRepository.cs
source/DasBlog.Web.Repositories/SiteSecurityRepository.cs
source/DasBlog.Web.UI/Controllers/AccountController.cs
source/DasBlog.Web.UI/DasBlog.Web.UI.csproj
source/DasBlog.Web.UI/Mappers/ProfileDasBlogUser.cs
source/DasBlog.Web.UI/Models/AccountViewModels/LoginViewModel.cs
source/DasBlog.Web.UI/Models/AccountViewModels/RegisterViewModel.cs
source/DasBlog.Web.UI/Models/Identity/ApplicationDbContext.cs
source/DasBlog.Web.UI/Models/Identity/ApplicationUser.cs
source/DasBlog.Web.UI/Models/Identity/DasBlogRole.cs
source/DasBlog.Web.UI/Models/Identity/DasBlogUser.cs
source/DasBlog.Web.UI/Models/Identity/DasBlogUserRoleStore.cs
source/DasBlog.Web.UI/Models/Identity/DasBlogUserStore.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs
source/DasBlog.Web.UI/Startup.cs
source/DasBlog.Web.UI/Views/Account/Login.cshtml
source/DasBlog.Web.UI/Views/Account/Register.cshtml
source/DasBlog.Web.UI/Views/Account/Register.cshtml.cs
source/DasBlog.Web.UI/Views/Shared/_Layout.cshtml
source/DasBlog.Web.UI/Views/Shared/_LoginPartial.cshtml
source/DasBlog.Web.UI/Views/Shared/_LoginPartial.cshtml.cs

Think i got all the plumbing done but back-end sitesecurityconfig isn't loading the xml data. Will have to look at that.

Aspnetcore identity

---

source/DasBlog.Web.UI/Startup.cs

Profile post was no longer part of the auto mapper profile.

Need to resolve an issue with automapper.

---

source/DasBlog.Web.UI/Controllers/AccountController.cs
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Mappers/ProfileDasBlogUser.cs
source/DasBlog.Web.UI/Models/Identity/DasBlogPasswordHasher.cs
source/DasBlog.Web.UI/Models/Identity/DasBlogUser.cs
source/DasBlog.Web.UI/Models/Identity/DasBlogUserStore.cs
source/DasBlog.Web.UI/Views/Shared/_LoginPartial.cshtml

Managed to integrate with old password hash.

Finished integrating security

---

README.md

Changes the instructions for making changes to the REPO

Update reade me

---

source/DasBlog.Web.UI/TagHelpers/AuthorizationRoleTagHelper.cs
source/DasBlog.Web.UI/TagHelpers/UnAuthorizedRoleTagHelper.cs
source/DasBlog.Web.UI/Themes/DasBlog/_CommentPartial.cshtml
source/DasBlog.Web.UI/Themes/DasBlog/_Layout.cshtml
source/DasBlog.Web.UI/Themes/DasBlog/_PostPartial.cshtml
source/DasBlog.Web.UI/Views/Shared/_LoginPartial.cshtml

Closes #58 this allows us to attach an dasblog-authorized or dasblog-unauthorize to any html element to hide or reveal authenticated/unauthenticated items depending on whether you are signed in or not.

Admin bar taghelper

---

.gitignore
source/DasBlog.Web.Repositories/DasBlog.Managers.csproj

git ignore the .idea directory and add some reference that vs appears to find unnecessary

Support rider ide

---

source/DasBlog.Web.UI/Settings/DasBlogSettings.cs
source/DasBlog.Web.UI/Themes/DasBlog/_Layout.cshtml

Issue 99: allow app to be served up by Kestrel etc. without needing to change site.config.  This also more flexible in the face of multiple different address scenarios such as ip address vs. DNS.

Run without iis express

---

source/DasBlog.Web.UI/Identity/DasBlogUserStore.cs
source/DasBlog.Web.UI/Startup.cs

Addresses No way to view unpublished posts #50

display unpublished posts if user has the admin role

---

source/DasBlog.Tests/Config/siteSecurity.config
source/DasBlog.Tests/Services/UserDataRepoTest.cs
source/DasBlog.Web.Core/Services/UserDataRepo.cs
source/DasBlog.Web.UI/Config/siteSecurity.config

addresses issue Change siteSecurity.Config back #118

change root of siteSecurity.config from Site...Data to SiteSecurityConfig

---

source/DasBlog.Web.UI/TagHelpers/PostToFacebookTagHelper.cs
source/DasBlog.Web.UI/TagHelpers/PostToTwitterTagHelper.cs
source/DasBlog.Web.UI/Themes/DasBlog/_PostPartial.cshtml

Closes a couple of the oldest issues.

Social taghelpers

---

source/ContributorFAQ.md
source/DasBlog All.sln

Please link to the FAQ or move it as you see fit.   It is a working document

Contributor faq

---

source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs

Default posts are not based on unique days.

Fixed base url

---

source/DasBlog.Tests/UnitTests/DasBlog.Tests.UnitTests.csproj
source/DasBlog.Tests/UnitTests/Managers/SiteSecurityManagerTest.cs
source/DasBlog.Tests/UnitTests/Services/ActivityRepoTest.cs
source/DasBlog.Tests/UnitTests/Services/ActivityServiceTest.cs
source/DasBlog.Tests/UnitTests/Services/BlogDataServiceTest.cs
source/DasBlog.Tests/UnitTests/Services/EntryCollectionTest.cs
source/DasBlog.Tests/UnitTests/Services/EventLineParserTest.cs
source/DasBlog.Tests/UnitTests/Services/UserDataRepoTest.cs
source/DasBlog.Tests/UnitTests/TestContent/2003-07-31.dayentry.xml
source/DasBlog.Tests/UnitTests/TestContent/2003-08-01.dayentry.xml
source/DasBlog.Tests/UnitTests/TestContent/2004-01-13.dayentry.xml
source/DasBlog.Tests/UnitTests/TestContent/2004-01-25.dayentry.xml
source/DasBlog.Tests/UnitTests/TestContent/2004-02-06.dayentry.xml
source/DasBlog.Tests/UnitTests/TestContent/2004-02-19.dayentry.xml
source/DasBlog.Tests/UnitTests/TestContent/2004-03-01.dayentry.xml
source/DasBlog.Tests/UnitTests/TestContent/2004-03-02.dayentry.xml
source/DasBlog.Tests/UnitTests/TestContent/2004-03-14.dayentry.xml
source/DasBlog.Tests/UnitTests/TestContent/2004-03-27.dayentry.xml
source/DasBlog.Tests/UnitTests/TestEntry.cs
source/DasBlog.Tests/UnitTests/UI/TagHelperTest.cs
source/DasBlog.Tests/UnitTests/UnitTestsConstants.cs
source/DasBlog.Web.Repositories/BlogManager.cs

Creates a bunch more unit tests that will be executed with appveyor. NewIntelligence Unit test project will soon be obsolete.

Appveyor test unit fix

---

README.md
source/DasBlog.Web.UI/DasBlog.Web.csproj

A little more deployment info for IIS via Visual Studio

Better deployment

---

source/DasBlog.Tests/UnitTests/DasBlogSettingTest.cs
source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Tests/UnitTests/UI/TagHelperTest.cs
source/DasBlog.Web.UI/TagHelpers/CommentPostTagHelper.cs
source/DasBlog.Web.UI/TagHelpers/DeletePostTagHelper.cs
source/DasBlog.Web.UI/TagHelpers/EditPostTagHelper.cs
source/DasBlog.Web.UI/Themes/DasBlog/_PostPartial.cshtml

Fixed tag helpers for comments and deletes

Taghelper routes fixes

---

source/DasBlog.Web.UI/Controllers/ActivityController.cs
source/DasBlog.Web.UI/Themes/DasBlog/_CommentPartial.cshtml
source/DasBlog.Web.UI/Views/Activity/ActivityList.cshtml
source/DasBlog.Web.UI/Views/Users/Components/UserList/Default.cshtml

Fixed formatting on post comments
Fixed relative path on ActivityList page
Fixed relative path on Users page

Fixed relative path on ActivityController

---

README.md
source/Lesnikowski.Pawel.Mail.Pop3/Lesnikowski.Pawel.Mail.Pop3.csproj
source/Subtext.Akismet/Subtext.Akismet.csproj
source/WebControlCaptcha/WebControlCaptcha.vbproj
source/newtelligence.DasBlog.Runtime.Proxies/newtelligence.DasBlog.Runtime.Proxies.csproj
source/newtelligence.DasBlog.Runtime/Test/newtelligence.DasBlog.runtime.Test.csproj
source/newtelligence.DasBlog.Runtime/newtelligence.DasBlog.Runtime.csproj
source/newtelligence.DasBlog.Util/Test/newtelligence.DasBlog.Util.Test.csproj
source/newtelligence.DasBlog.Util/newtelligence.DasBlog.Util.csproj
source/newtelligence.DasBlog.Web.Core/Test/newtelligence.DasBlog.Web.Core.Test.csproj
source/newtelligence.DasBlog.Web.Core/newtelligence.DasBlog.Web.Core.csproj
source/newtelligence.DasBlog.Web.Services/newtelligence.DasBlog.Web.Services.csproj
source/newtelligence.DasBlog.Web/Web.config
source/newtelligence.DasBlog.Web/newtelligence.DasBlog.Web.csproj

Upgraded projects to 4.7.2 from 4.6.1

#162 upgrade projects to 4.7.2

---

README.md
source/DasBlog.Web.Repositories/BlogManager.cs
source/Lesnikowski.Pawel.Mail.Pop3/Lesnikowski.Pawel.Mail.Pop3.csproj
source/Subtext.Akismet/Subtext.Akismet.csproj
source/WebControlCaptcha/WebControlCaptcha.vbproj
source/newtelligence.DasBlog.Runtime.Proxies/newtelligence.DasBlog.Runtime.Proxies.csproj
source/newtelligence.DasBlog.Runtime/Test/newtelligence.DasBlog.runtime.Test.csproj
source/newtelligence.DasBlog.Runtime/newtelligence.DasBlog.Runtime.csproj
source/newtelligence.DasBlog.Util/Test/newtelligence.DasBlog.Util.Test.csproj
source/newtelligence.DasBlog.Util/newtelligence.DasBlog.Util.csproj
source/newtelligence.DasBlog.Web.Core/Test/newtelligence.DasBlog.Web.Core.Test.csproj
source/newtelligence.DasBlog.Web.Core/newtelligence.DasBlog.Web.Core.csproj
source/newtelligence.DasBlog.Web.Services/newtelligence.DasBlog.Web.Services.csproj
source/newtelligence.DasBlog.Web/Web.config
source/newtelligence.DasBlog.Web/newtelligence.DasBlog.Web.csproj

If the search string is empty then I've made it return all the results, I can change this behaviour though if desired.

Blank search error

---

source/DasBlog.Web.Repositories/SubscriptionManager.cs
source/DasBlog.Web.Repositories/XmlRpcManager.cs
source/DasBlog.Web.UI/Controllers/FeedController.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs
source/DasBlog.Web.UI/wwwroot/js/site.js
source/DasBlog.Web.UI/wwwroot/js/site.min.js

Fixes integration with Livewriter 
...also the delete post link.

Live writer fix

---

source/DasBlog.Web.UI/Controllers/AccountController.cs
source/DasBlog.Web.UI/Controllers/ArchiveController.cs
source/DasBlog.Web.UI/Controllers/CategoryController.cs
source/DasBlog.Web.UI/Controllers/DasBlogBaseController.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs
source/DasBlog.Web.UI/Themes/DasBlog/_Layout.cshtml
source/DasBlog.Web.UI/Views/Users/Components/UserList/Default.cshtml

This is not a clean pull and fixes multiple un documented issues.
Also closes #203

Misc fixes

---

source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/TagHelpers/TitleLinkTagHelper.cs
source/DasBlog.Web.UI/Themes/fulcrum/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/_BlogItemSummary.cshtml
source/DasBlog.Web.UI/Themes/median/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/median/_BlogItemSummary.cshtml

Added css and js to the build output
Modified templates to use title tags

Fixed Title tag.

---

source/DasBlog.Web.Repositories/SiteManager.cs

Fix for site map

---

source/DasBlog.Web.Repositories/SubscriptionManager.cs
source/DasBlog.Web.Repositories/XmlRpcManager.cs
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Controllers/FeedController.cs
source/newtelligence.DasBlog.Web.Services/Rsd.cs

Fix blogging rsd

---

source/DasBlog.Web.Core/Common/Utils.cs
source/DasBlog.Web.Repositories/CategoryManager.cs
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Mappers/ProfilePost.cs
source/newtelligence.DasBlog.Runtime/Entry.cs

Consistent renaming.
Fixed category search

Fixes category issues.

---

source/DasBlog.Web.UI/Controllers/DasBlogBaseController.cs

Fixes an issue where Twitter summary cards are broken.

Fix for twitter cards, missing description

---

source/DasBlog.Web.UI/Views/Shared/_TwitterCardPartial.cshtml

removed a single misplaced character

---

source/DasBlog.Web.Core/Configuration/IMetaTags.cs
source/DasBlog.Web.Core/Configuration/MetaTags.cs
source/DasBlog.Web.Core/DasBlog.Core.csproj
source/DasBlog.Web.Core/Services/Rss/Rsd.cs
source/DasBlog.Web.Core/Services/Rss/Rss.cs
source/DasBlog.Web.Repositories/Interfaces/ISubscriptionManager.cs
source/DasBlog.Web.Repositories/SubscriptionManager.cs
source/DasBlog.Web.UI/Config/metaConfig.xml
source/DasBlog.Web.UI/Controllers/FeedController.cs

Improve integration with Feedly which for now includes a logo and also the use google analytics tracking.

Initial and probably complete check in

---

source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Controllers/DasBlogController.cs
source/DasBlog.Web.UI/Controllers/FeedController.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs

Got some basic caching in place.

Cache main page

---

source/DasBlog.Web.Repositories/CategoryManager.cs
source/DasBlog.Web.Repositories/Interfaces/ICategoryManager.cs
source/DasBlog.Web.UI/Controllers/CategoryController.cs
source/DasBlog.Web.UI/Controllers/FeedController.cs
source/DasBlog.Web.UI/Startup.cs
source/DasBlog.Web.UI/content/2018-02-24.dayentry.xml
source/newtelligence.DasBlog.Runtime/BlogDataService.cs
source/newtelligence.DasBlog.Runtime/CategoryCache.cs
source/newtelligence.DasBlog.Runtime/IBlogDataService.cs

changes the url format
Fixes the category page when a specific category is selected.

Fixes for inconsistent categories

---

source/DasBlog.Services/DasBlog.Services.csproj
source/DasBlog.Tests/FunctionalTests/BrowserBasedTests/BrowserBasedTestsBase.cs
source/DasBlog.Tests/FunctionalTests/BrowserBasedTests/BrowserTestPlatform.cs
source/DasBlog.Tests/FunctionalTests/BrowserBasedTests/PageControlTests.cs
source/DasBlog.Tests/FunctionalTests/DasBlog.Tests.FunctionalTests.csproj
source/DasBlog.Tests/UnitTests/DasBlog.Tests.UnitTests.csproj
source/DasBlog.Web.Repositories/XmlRpcManager.cs
source/DasBlog.Web.UI/Program.cs

- I fixed that Razor error
- I changed the 2001 RPC Dependency to https://github.com/LordVeovis/xmlrpc
- Added a Skip for tests that need to not run during Live Unit Testing (LUT)

Fixed Razor Design error, changed RPC dependancy

---

source/DasBlog.Tests/UnitTests/DasBlogSettingTest.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs
source/DasBlog.Web.UI/Controllers/SiteController.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs

Microsummary fix

---

source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.Production.config
source/DasBlog.Web.UI/Program.cs

moving to site.environment.config model

moving to site.environment.config model

---

source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Tests/UnitTests/Config/site.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/Properties/launchSettings.json
source/DasBlog.Web.UI/Startup.cs

Please read this carefully. We're using wildcards now. Config is copied, Default Themes are PACKED, except the themes YOU add.

Trying a new way to copy themes. Everything BUT defaults. TEST THIS

---

source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.Production.config
source/DasBlog.Web.UI/Views/Archive/Archive.cshtml
source/DasBlog.Web.UI/appsettings.json

Fixed urls for development.
Fixed the archive view needed to look at a list of ViewModels

Several fixes

---

source/DasBlog.Tests/FunctionalTests/ComponentTests/ComponentTestPlatform.cs
source/DasBlog.Tests/UnitTests/UI/TagHelperTest.cs
source/DasBlog.Web.Repositories/BlogManager.cs
source/DasBlog.Web.Repositories/Interfaces/IBlogManager.cs
source/DasBlog.Web.Repositories/SiteManager.cs
source/DasBlog.Web.Repositories/SubscriptionManager.cs
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/TagHelpers/CommentPostTagHelper.cs

switched from using the GUID to the name of the post.
Cleaned up some other code I simply did not understand.

Fix comment url

---

source/DasBlog.Web.Repositories/BlogManager.cs
source/DasBlog.Web.UI/Config/IISUrlRewrite.xml
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs
source/DasBlog.Web.UI/Models/BlogViewModels/ListCommentsViewModel.cs
source/DasBlog.Web.UI/Views/Shared/_CommentBlockPartial.cshtml

Fixing comments count
Viewing comments while viewing a specific post is connected to "ShowCommentsWhenViewingEntry".
Fixing comment redirect.

Comments not counted

---

source/DasBlog.Web.Repositories/SubscriptionManager.cs

Should allow for some tracking and extra image detection in a service like Feedly.

Fixed the namespace associated with the webfeeds elements.

---

source/DasBlog.Web.Repositories/ArchiveManager.cs
source/DasBlog.Web.Repositories/BlogManager.cs
source/DasBlog.Web.Repositories/CategoryManager.cs
source/DasBlog.Web.Repositories/FileSystemBinaryManager.cs
source/DasBlog.Web.Repositories/SiteManager.cs
source/DasBlog.Web.Repositories/SiteSecurityManager.cs
source/DasBlog.Web.Repositories/SubscriptionManager.cs
source/DasBlog.Web.Repositories/XmlRpcManager.cs
source/DasBlog.Web.UI/DasBlog.Web.csproj

nothing big, removing some unnecessary comments, and some readonly private variables...

Quick clean up of some code

---

README.md

Adding badges for each OS DevOps Builds on.

OS Specific Build Badges

---

source/DasBlog.Web.Repositories/XmlRpcManager.cs
source/DasBlog.Web.UI/Controllers/FeedController.cs
source/DasBlog.Web.UI/TagHelpers/CategoriesListTagHelper.cs

Need more logging around live writer posts (/blogger).
Also more defensive checks when posts do not have categories.

Clean code add logging

---

source/DasBlog.Web.UI/Views/Shared/_CommentPartial.cshtml

Removed an unnecessary semi colon.

Removed an error with comments

---

source/DasBlog.Services/IDasBlogSettings.cs
source/DasBlog.Tests/UnitTests/DasBlogSettingTest.cs
source/DasBlog.Web.Repositories/SiteManager.cs
source/DasBlog.Web.UI/Controllers/CategoryController.cs
source/DasBlog.Web.UI/Mappers/ProfilePost.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs
source/DasBlog.Web.UI/Views/Category/Category.cshtml

Fixed category name in sitemap
Fixed category links on category page.

Fix category names sitemap

---

source/DasBlog.Web.UI/Themes/DasBlog/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/DasBlog/_BlogItemSummary.cshtml
source/DasBlog.Web.UI/Themes/DasBlog/_BlogPage.cshtml
source/DasBlog.Web.UI/Themes/DasBlog/_BlogPageSummary.cshtml
source/DasBlog.Web.UI/Themes/DasBlog/_Layout.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/_BlogPage.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/_BlogPageSummary.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/_Layout.cshtml
source/DasBlog.Web.UI/Themes/median/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/median/_BlogPage.cshtml
source/DasBlog.Web.UI/Themes/median/_BlogPageSummary.cshtml
source/DasBlog.Web.UI/Themes/median/_Layout.cshtml
source/DasBlog.Web.UI/Views/BlogPost/CreatePost.cshtml
source/DasBlog.Web.UI/Views/BlogPost/EditPost.cshtml
source/DasBlog.Web.UI/Views/Shared/_BlogItems.cshtml
source/DasBlog.Web.UI/Views/Shared/_BlogItemsSummary.cshtml
source/DasBlog.Web.UI/Views/Shared/_CommentBlockPartial.cshtml
source/DasBlog.Web.UI/Views/Users/CreateUser.cshtml
source/DasBlog.Web.UI/Views/Users/DeleteUser.cshtml
source/DasBlog.Web.UI/Views/Users/EditUser.cshtml
source/DasBlog.Web.UI/Views/Users/Maintenance.cshtml
source/DasBlog.Web.UI/Views/Users/ViewUser.cshtml
source/DasBlog.Web.UI/Views/Users/_UsersLayout.cshtml

Removes the use of HtmlHelper from razor pages

Partial async view fix

---

source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config

Moving the  EnableStartPageCaching  element up so that it is clear that thi…s is a setting that is required/used setting.
This change does not break anything, just updates the default layout...

Update the layout of SiteConfig

---

source/DasBlog.Web.UI/Properties/launchSettings.json

Just in case folks would like to run locally using IIS Express.

Fix launch settings for IIS Express

---

source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/Startup.cs

Support runtime Razor compilation

---

source/DasBlog.Web.UI/Controllers/FeedController.cs

This always worked for my local testing, still not sure why this fails after deploy ... so here we are 🤞

Make the action async

---

source/DasBlog.Web.Core/Common/Constants.cs
source/DasBlog.Web.Repositories/FileSystemBinaryManager.cs
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Startup.cs
source/DasBlog.Web.UI/TagHelpers/RichEdit/FroalaBuilder.cs
source/DasBlog.Web.UI/TagHelpers/RichEdit/IRichEditBuilder.cs
source/DasBlog.Web.UI/Views/Shared/_CommentPartial.cshtml

This resolves the issue where URLs being broken when editing blog post on the site. I am adding a new html editor (froala) that appears to be working more consistently. It also does not constantly remind you that it is not a "pro" edition..

Fix Image breaking issues on edit

---

source/DasBlog.Web.UI/Startup.cs

Moved location of the UseAuthorization(). Not sure why this is showing up as an issue now...

Quick auth fix

---

source/DasBlog.Services/FileManagement/ConfigFilePathsDataOption.cs
source/DasBlog.Web.UI/Services/DasBlogHealthChecks.cs
source/DasBlog.Web.UI/Startup.cs

(Except binary folder, I am not sure what this is for)

Basic health check

---

source/DasBlog.Services/IDasBlogSettings.cs
source/DasBlog.Tests/UnitTests/DasBlogSettingTest.cs
source/DasBlog.Web.UI/Controllers/AdminController.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

Attempting to make the Site Admin page a bit more responsive to saves. Some limitations as I am not sure how to access and update IServiceCollections after startup. For example, you may need a site restart in order to refresh the site theme.

Refresh settings

---

source/DasBlog.Web.Core/Common/Comments/Tag.cs
source/DasBlog.Web.Core/Common/Comments/ValidCommentTags.cs
source/DasBlog.Web.Repositories/FileSystemBinaryManager.cs
source/DasBlog.Web.UI/Controllers/AdminController.cs
source/DasBlog.Web.UI/Mappers/ProfilePost.cs
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/Models/AdminViewModels/TagViewModel.cs
source/DasBlog.Web.UI/Models/AdminViewModels/ValidCommentTagsViewModel.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

We are now able to save and retrieve Valid comment tags sections in the admin page.

Valid comment tags available in Admin page

---

source/DasBlog.Web.UI/Controllers/ActivityController.cs
source/DasBlog.Web.UI/Themes/DasBlog/_Layout.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/_Layout.cshtml
source/DasBlog.Web.UI/Themes/median/_Layout.cshtml
source/DasBlog.Web.UI/Views/Activity/ActivityList.cshtml

Fix for the activity list pages.

---

source/DasBlog.Services/ActivityLogs/EventCodes.cs
source/DasBlog.Web.UI/Controllers/AccountController.cs
source/DasBlog.Web.UI/Controllers/AdminController.cs
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Controllers/FeedController.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs
source/DasBlog.Web.UI/Controllers/SiteController.cs
source/DasBlog.Web.UI/Controllers/UsersController.cs

lets make sure we have some things getting logged.

Now that I have fixed the activity log page..

---

azure-pipelines.yml
source/DasBlog.Web.UI/Services/DasBlogHealthChecks.cs
source/DasBlog.Web.UI/Startup.cs

Getting actual error messages in logs on /healthcheck, also updating to .NET 3.1

Getting actual error messages in logs on /healthcheck, also updating to .NET 3.1

---

source/DasBlog.Web.UI/TagHelpers/Post/PostContentTagHelper.cs

Allow post content to optionally strip html and cut length.

More options for post content TagHelper

---

source/DasBlog.Web.UI/TagHelpers/TitleLinkTagHelper.cs

Allows you to change the name of the link as in "continue reading..."

More versatile Title TagHelper

---

source/DasBlog.Web.UI/TagHelpers/Site/SiteSearchBoxTagHelper.cs
source/DasBlog.Web.UI/Themes/DasBlog/_BlogPage.cshtml

Again focused on name consistency for taghelpers.

Update the Site search button.

---

source/DasBlog.Web.UI/TagHelpers/Site/SitePageControlTagHelper.cs
source/DasBlog.Web.UI/Themes/median/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/median/_BlogItemSummary.cshtml

Allows you to exclude the seperator and define CSS for each paging link

More versatile paging links

---

source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/TagHelpers/Site/SitePageControlTagHelper.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

Added content lookahead.
Fixed Range value
Also I fixed issues with "site page" tag helper control

Content look ahead

---

source/DasBlog.Web.UI/Settings/DasBlogSettings.cs

Noticed the icon reference was a jpeg

changing to an ico

---

source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Mappers/ProfilePost.cs
source/DasBlog.Web.UI/Models/BlogViewModels/CommentViewModel.cs
source/DasBlog.Web.UI/Models/BlogViewModels/SpamStateViewModel.cs
source/DasBlog.Web.UI/TagHelpers/Comments/CommentApprovalLinkTagHelper.cs

Fixing delete comments
Enhanced status for new comments

Comment issues

---

source/DasBlog All.sln
source/DasBlog.CLI/DasBlog.CLI.csproj
source/DasBlog.CLI/InitializeConfigFiles.cs
source/DasBlog.CLI/Program.cs
source/DasBlog.CLI/dasblog-core.runtimeconfig.json
source/DasBlog.Services/ConfigFile/Interfaces/ISiteSecurityConfig.cs
source/DasBlog.Services/ConfigFile/SiteSecurityConfig.cs
source/DasBlog.Services/ConfigFile/SiteSecurityConfigData.cs
source/DasBlog.Services/FileManagement/SiteSecurityConfigFileService.cs
source/DasBlog.Services/Users/IUserDataRepo.cs
source/DasBlog.Services/Users/UserDataRepo.cs
source/DasBlog.Services/Users/UserService.cs
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Controllers/UsersController.cs
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/Program.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs
source/DasBlog.Web.UI/Startup.cs

Wanted to make it easier to initialize a new site from CLI on Azure App Services.

Initialize new site

---

source/DasBlog.Tests/DasBlog.Test.Integration/SeleniumPageTests.cs
source/DasBlog.Web.UI/Views/Archive/Archive.cshtml
source/DasBlog.Web.UI/wwwroot/css/site.css

A quick fix of the calendar page. Updates the site.css file If you are not using the default cal you will be not be impacted.

Calendar page CSS fixes

---

source/DasBlog.Web.UI/Models/AdminViewModels/ThemesListViewModel.cs
source/DasBlog.Web.UI/Views/Archive/Archive.cshtml
source/DasBlog.Web.UI/wwwroot/css/site.css

I think this is… the last one.
Also fixed another small CSS faux pas.

Fixed and issue with bad folder seperator assumption.

---

source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/TagHelpers/RichEdit/FroalaBuilder.cs
source/DasBlog.Web.UI/TagHelpers/RichEdit/NicEditBuilder.cs
source/DasBlog.Web.UI/TagHelpers/RichEdit/TextAreaBuilder.cs
source/DasBlog.Web.UI/TagHelpers/RichEdit/TinyMceBuilder.cs
source/DasBlog.Web.UI/Views/BlogPost/BlogPostFields.cshtml
source/DasBlog.Web.UI/wwwroot/css/site.css

Low impact change.
Helps ensure that the section does not overlap with categories.

Create post has minimum height 

---

source/DasBlog.Web.UI/Models/UsersViewModel.cs

Just a simple change to fix a typo.  I am not sure if I am doing this properly so please let me know if I should be doing something differently.

Changed dipslay name to display name on the Users view model.

---

source/DasBlog.Tests/UnitTests/UI/TagHelperTest.cs
source/DasBlog.Web.UI/TagHelpers/CommentPostTagHelper.cs
source/DasBlog.Web.UI/Themes/darkly/_BlogItemSummary.cshtml
source/DasBlog.Web.UI/Themes/darkly/_BlogPageSummary.cshtml

Upgraded CommentPostTagHelper to allow custom link text.  Also added a unit test.
Updated darkly theme to respect the ShowItemSummaryInAggregatedViews setting.

darkly theme modification and upgrade to CommentPostTagHelper 

---

source/DasBlog.Web.UI/Themes/DasBlog/_BlogItemSummary.cshtml
source/DasBlog.Web.UI/Themes/DasBlog/_BlogPageSummary.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/_BlogItemSummary.cshtml
source/DasBlog.Web.UI/Themes/journal/_BlogItemSummary.cshtml
source/DasBlog.Web.UI/Themes/journal/_BlogPageSummary.cshtml

Corrected the DasBlog and journal themes to respect the ShowItemSummaryInAggregatedViews setting.
Corrected a typo in the fulcrum theme that was causing an error when trying to use the ShowItemSummaryInAggregatedViews setting.

Corrected themes to respect ShowItemSummaryInAggregatedViews setting.

---

source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/TagHelpers/CommentPostTagHelper.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

Should be fairly straightforward...

Added comment count settings to the tag helper and the admin page

---

source/DasBlog.Web.UI/Controllers/ArchiveController.cs
source/DasBlog.Web.UI/Controllers/CategoryController.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs
source/DasBlog.Web.UI/appsettings.Development.json
source/DasBlog.Web.UI/appsettings.json

Wanted to add some low level logging.

More logging 

---

source/DasBlog.Web.UI/Themes/DasBlog/_BlogPageSummary.cshtml
source/DasBlog.Web.UI/Themes/median/_BlogItem.cshtml
source/DasBlog.Web.UI/Views/Archive/Archive.cshtml

Just like the title says.  Changed all usages of obsolete tag helpers to the new tag helpers.

Banished the use of all obsolete tag helpers.

---

source/DasBlog.CLI/Program.cs
source/DasBlog.Tests/DasBlog.Test.Integration/SeleniumPageTests.cs
source/DasBlog.Web.UI/Controllers/AdminController.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

Reloads configuration data after a save by using IOptionsMonitor

IOption config update

---

source/DasBlog.Web.Repositories/XmlRpcManager.cs

This value ensures we do not modify the blog contents.

Removes text appended in OLW

---

source/DasBlog.Web.Repositories/XmlRpcManager.cs

Allows users to pull as many Open Live Writer posts as they wish.

Open Live Writer Post retrieval fix

---

source/DasBlog.Services/IDasBlogSettings.cs
source/DasBlog.Tests/UnitTests/DasBlogSettingTest.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs
source/DasBlog.Web.UI/TagHelpers/Comments/CommentUserHomePageLink.cs
source/DasBlog.Web.UI/Views/Shared/_CommentPartial.cshtml

If you do not specify a home page address it would link to the home page of the site. **Fixed**
Comment from admin have CSS that will allow you to highlight

Fix comment homepage link 

---

source/DasBlog.Web.UI/TagHelpers/Comments/CommentGravatarImageTagHelper.cs
source/DasBlog.Web.UI/Views/Shared/_CommentPartial.cshtml

This is using Bootstrap, you would copy and update this file in your themes folder if you want to the layout changed.

More coherent layout for comments

---

source/DasBlog.Web.UI/Controllers/DasBlogBaseController.cs
source/DasBlog.Web.UI/Mappers/ProfileDasBlogUser.cs
source/DasBlog.Web.UI/Mappers/ProfilePost.cs
source/DasBlog.Web.UI/Models/BlogViewModels/PostViewModel.cs
source/DasBlog.Web.UI/Views/Shared/_OpenGraphPartial.cshtml

Specifically adds this to head section <meta property='og:video'  />
Only does this when you land on a blog pages...

Adds open graph meta data

---

source/DasBlog.Web.UI/Themes/darkly/_BlogItemSummary.cshtml
source/DasBlog.Web.UI/Themes/darkly/_BlogPageSummary.cshtml
source/DasBlog.Web.UI/Themes/dasblog/_BlogItemSummary.cshtml
source/DasBlog.Web.UI/Themes/dasblog/_BlogPageSummary.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/_BlogItemSummary.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/_BlogPageSummary.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/custom.css
source/DasBlog.Web.UI/Themes/journal/_BlogItemSummary.cshtml
source/DasBlog.Web.UI/Themes/journal/_BlogPageSummary.cshtml
source/DasBlog.Web.UI/Themes/median/_BlogItemSummary.cshtml
source/DasBlog.Web.UI/Views/Shared/_CommentBlockPartial.cshtml
source/DasBlog.Web.UI/Views/Shared/_CommentPartial.cshtml

This PR updates the themes associated with Front Page Summary configuration (ShowItemSummaryInAggregatedViews = true) and ensures that they are functioning correctly.

Fix summary portion of the theme

---

source/DasBlog.Web.Repositories/BlogManager.cs
source/DasBlog.Web.UI/Mappers/ProfilePost.cs

Had some issues with unique URLs. If enabled **Enable unique URls** in the site admin page it would only be honored on the home page. Now this works on the category page and within the RSS feed.

Ensure everything works for Unique URLS.

---

source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/TagHelpers/SearchBoxTagHelper.cs
source/DasBlog.Web.UI/TagHelpers/Site/SiteSearchBoxTagHelper.cs
source/DasBlog.Web.UI/Themes/median/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/median/_Layout.cshtml

- Made the Post search URL action consistent with the others.
- The search tag helper now uses the **Root** URL
- Started using the site search tag helper in place of a manually designed post search.

Search page updates

---

CONTRIBUTING.md
FAQ.md
README.md

Updating readme, FAQ and contribution docs...

Documentation update

---

source/DasBlog.CLI/DasBlog.CLI.csproj
source/DasBlog.Services/ActivityLogs/EventCodes.cs
source/DasBlog.Services/DasBlog.Services.csproj
source/DasBlog.Services/IDasBlogSettings.cs
source/DasBlog.Services/Scheduler/SiteReport.cs
source/DasBlog.Tests/UnitTests/DasBlogSettingTest.cs
source/DasBlog.Web.Repositories/BlogManager.cs
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/Services/LoggingAgent.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs
source/DasBlog.Web.UI/Startup.cs
source/DasBlog.Web.UI/appsettings.json
source/newtelligence.DasBlog.Runtime/BlogDataService.cs

If enabled you get an daily email that highlights that number of visitors by domain, referrers and user agent.

Daily Email alert

---

source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Controllers/DasBlogBaseController.cs
source/DasBlog.Web.UI/Models/BlogViewModels/ListCommentsViewModel.cs
source/DasBlog.Web.UI/Models/BlogViewModels/PostViewModel.cs
source/DasBlog.Web.UI/Views/Shared/_CommentBlockPartial.cshtml

Fix for Issue #458 where the comment was getting lost if the user entered invalid spam value or forgot filing the captcha button.

Fix For Issue 458. Comment Now Shows Relevant Errors.

---

azure-pipelines.yml
source/DasBlog.Services/ConfigFile/Interfaces/ISiteConfig.cs
source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/Startup.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

Improves the security of dasblog.
Doing a minor version bump as we change the site.config, however, the change will work with files without the config elements.
Going to the admin page and saving will allow anyone to define there own values.

Security headers

---

source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config

Include the bootstrap site as part of the default security header.

Needed to include bootstrap stylesheet as that defines the basic style

---

source/DasBlog.Web.UI/Config/IISUrlRewrite.Development.config
source/DasBlog.Web.UI/Controllers/FeedController.cs
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/Startup.cs
source/DasBlog.Web.UI/Themes/_ViewImports.cshtml

This adds appinsights, closes #473 and starts work on #474. Unless we are just returning OK on comments, then it closes #474 as designed

Adding better rewrites, HEAD on feeds, broken link

---

source/DasBlog.Web.UI/Startup.cs

Adding cache control headers to static files. We had none

Adding cache control headers to static files. We had none

---

source/DasBlog.Web.UI/TagHelpers/Site/SitePageControlTagHelper.cs

Hi, 
I fixed issue #464, I hope you marge it :)

Fixed Issue #464

---

source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs

Fixed Issue #463

---

source/DasBlog.Services/IDasBlogSettings.cs
source/DasBlog.Tests/UnitTests/DasBlogSettingTest.cs
source/DasBlog.Web.Repositories/SubscriptionManager.cs
source/DasBlog.Web.UI/Controllers/DasBlogBaseController.cs
source/DasBlog.Web.UI/Identity/DasBlogUserStore.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs

Fixed Html Header Author Error
Issue #466

Fixed Issue #466

---

source/DasBlog.Web.UI/Views/BlogPost/BlogPostFields.cshtml

Fixes poppastring/dasblog-core#494

save the Description field with the post

---

azure-pipelines.yml

Add condition to only echo buildinfo on linux

---

source/DasBlog.Web.UI/Controllers/UsersController.cs

This immediately stores the user/password update into memory.

Password updates no longer need a restart

---

source/DasBlog.Tests/UnitTests/Services/IdentityOptionsConfigurationTests.cs
source/DasBlog.Tests/UnitTests/appsettings.json
source/DasBlog.Web.UI/Startup.cs
source/DasBlog.Web.UI/appsettings.json

Sort of thing that a user might want to change but shouldn't require a code change

Move password constraints to appsettings

---

source/DasBlog.Web.UI/Program.cs

.NET Core 3.1 preferred startup

Flip to .NET Core HostBuilder and suppress the Kestrel header

---

source/DasBlog.Web.Repositories/BlogManager.cs
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config

We now support front page categories...

Front page category

---

source/DasBlog.Web.Repositories/SiteSecurityManager.cs

Refactored to remove class level hash algorithm variable that allowed for hash algorithm instance to be updated.
The fixes issue #516

Fixed issue where MD5 was always set for password hashing.

---

source/DasBlog.Web.UI/TagHelpers/Post/PostEditLinkTagHelper.cs
source/DasBlog.Web.UI/TagHelpers/Post/PostImageTagHelper.cs
source/DasBlog.Web.UI/TagHelpers/Post/PostLinkTagHelper.cs

New Post Image
New Post Link - can be used in combination with post image for link to blog post
Updated Post Edit to allow for setting edit link text, to allow changing text or removing text.

New and Enhanced Post Tag helpers

---

source/DasBlog.Tests/DasBlog.Test.Integration/SeleniumPageTests.cs
source/DasBlog.Web.UI/Controllers/AdminController.cs
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs
source/DasBlog.Web.UI/Themes/darkly/_BlogItem.cshtml
source/DasBlog.Web.UI/Views/Admin/ManageComments.cshtml

- Fixed when we break the cache if you edit a post
- Fixed broken integration tests

Quick fixes

---

source/DasBlog.CLI/InitializeConfigFiles.cs

Check if the file exists before attempting to save it.

Changed some assumptions about initializing a project

---

source/DasBlog.Web.UI/Startup.cs

In reference to #529 
I have remove line 
> context.Response.Headers.Add("Feature-Policy", ....
in StartUp.cs on **DasBlog.Web** Project

Remove Feature-Policy from Header

---

source/DasBlog.Web.UI/Startup.cs

In reference to #538 
1. Add services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
2. Move some cookie options from services.ConfigureApplicationCookie to services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie

Fix bug authorization when running on http

---

source/DasBlog.Web.UI/TagHelpers/Post/PostImageTagHelper.cs
source/DasBlog.Web.UI/Themes/darkly/_BlogItemSummary.cshtml

In reference to #555 
Updated :
1. PostImageTagHelper.cs
2. _BlogItemSummary.cshtml

Fix the BlogItemSummary razor page

---

source/DasBlog.Web.UI/Themes/darkly/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/dasblog/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/dasblog/_BlogPage.cshtml
source/DasBlog.Web.UI/Themes/fulcrum/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/journal/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/median/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/median/_Layout.cshtml
source/DasBlog.Web.UI/Views/Shared/_CollapseCommentBlockPartial.cshtml

On the front page you click a button to reveal the comment section.
Edited the other thenes to remove the search action.

Added a new collapsable control for comments. 

---

source/DasBlog.Web.UI/Settings/DasBlogSettings.cs

Submitting the PR so that users can keep comments open on their site forever and don't have to specify limitation in days. Fixes #567.

Fix for Bug #567

---

source/DasBlog.Web.Core/Common/Constants.cs
source/DasBlog.Web.UI/Controllers/ArchiveController.cs
source/DasBlog.Web.UI/Models/BlogViewModels/ArchiveListViewModel.cs
source/DasBlog.Web.UI/Views/Archive/ArchiveAll.cshtml

archive/all
Supports a single page with a complete listing the archived posts...

Allows for a single archive page that spans the history of the site.

---

source/DasBlog.Tests/DasBlog.Test.Integration/SeleniumPageTests.cs
source/DasBlog.Web.UI/content/2021-11-02.dayentry.xml

Updated the test to ignore text case

Fixed some of the unit test

---

azure-pipelines.yml
source/DasBlog.CLI/DasBlog.CLI.csproj
source/DasBlog.Services/DasBlog.Services.csproj
source/DasBlog.Tests/DasBlog.Test.Integration/DasBlog.Test.Integration.csproj
source/DasBlog.Tests/DasBlog.Test.Integration/SeleniumPageTests.cs
source/DasBlog.Tests/UnitTests/DasBlog.Tests.UnitTests.csproj
source/DasBlog.Tests/UnitTests/UnitTestsConstants.cs
source/DasBlog.Web.Core/DasBlog.Core.csproj
source/DasBlog.Web.Repositories/DasBlog.Managers.csproj
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/newtelligence.DasBlog.Runtime/newtelligence.DasBlog.Runtime.csproj

Update projects to .NET6
Update many of the Nuget Packages
Update CI/CD SDK to .NET 6

Upgrade dotnet 6

---

azure-pipelines.yml
source/DasBlog.Services/IDasBlogSettings.cs
source/DasBlog.Services/Site/TimeZoneProvider.cs
source/DasBlog.Tests/UnitTests/DasBlogSettingTest.cs
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Mappers/ProfilePost.cs
source/DasBlog.Web.UI/Settings/DasBlogSettings.cs

Fixing the lookahead calculation

Lookahead offset fix

---

source/DasBlog.Web.UI/Views/Admin/Settings.cshtml
source/DasBlog.Web.UI/wwwroot/css/site.css

Upgrading bootstrap left the admin page a little misaligned. This should resolve most of those issues.

Site admin required updates

---

source/DasBlog.CLI/dasblog-core.runtimeconfig.json

Updating the support to support net6.0

Updated the CLI tools runtime config

---

source/DasBlog.Web.UI/Config/site.Development.config

Needs access to socket for local hot reload development.

Updated the default source list to allow Hot Reload to work 

---

source/DasBlog.Web.UI/Controllers/ArchiveController.cs

Archive page is more consistent.

Ensure that dates account for any time index offsets

---

source/DasBlog.Web.UI/TagHelpers/Comments/CommentApprovalLinkTagHelper.cs
source/DasBlog.Web.UI/TagHelpers/Comments/CommentDeleteLinkTagHelper.cs
source/DasBlog.Web.UI/wwwroot/js/site.js

Updating/deleting the comment status will not switch pages on you.

Comment status updates will not switch pages

---

source/DasBlog.Web.UI/Controllers/ArchiveController.cs

Incorrectly updated the Entry for date values which impacted the cache.

Fixing archive

---

source/DasBlog.Web.UI/Controllers/BlogPostController.cs

Will have a more long term fix… for comments going forward.

Quick fix to remove double "encoding". 

---

source/DasBlog.Web.UI/Controllers/FeedController.cs

If the passed in category does not exist, we will no longer return any data at all.
This prevents injecting user data in the rss category title. 
Also prevents caching of essentially empty RSS data unnecessarily.

RSS category security fix

---

source/DasBlog.Tests/UnitTests/UI/PostToLinkedInTagHelperTest.cs
source/DasBlog.Web.UI/TagHelpers/Post/PostToLinkedInTagHelper.cs
source/DasBlog.Web.UI/Themes/darkly/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/dasblog/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/journal/_BlogItem.cshtml
source/DasBlog.Web.UI/Themes/median/_BlogItem.cshtml

This PR adds a share to linkedin tag helper.

feat: create a share to linkedin tag helper

---

source/DasBlog.Web.UI/TagHelpers/Comments/CommentGravatarImageTagHelper.cs

Set alt tag to some value to avoid html errors.

---

source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml
source/DasBlog.Web.UI/Views/BlogPost/BlogPostFields.cshtml
source/DasBlog.Web.UI/Views/BlogPost/CreatePost.cshtml
source/DasBlog.Web.UI/Views/BlogPost/EditPost.cshtml
source/DasBlog.Web.UI/Views/Users/ViewEditUser.cshtml

- We explicitly set the modified date to the UtcNow.
- A couple of semi-helpful UX fixes

Hopefully an actual fix for the edit issue.

---

source/DasBlog.Web.UI/DasBlog.Web.csproj

Embedded publish repo url
Embedded Symbol packaages

Added source link references.

---

source/DasBlog.CLI/DasBlog.CLI.csproj
source/DasBlog.Services/DasBlog.Services.csproj
source/DasBlog.Web.Core/DasBlog.Core.csproj
source/DasBlog.Web.Repositories/DasBlog.Managers.csproj
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/newtelligence.DasBlog.Runtime/newtelligence.DasBlog.Runtime.csproj

Makes debugging and diagnostics easier.

Source Link included in all projects.

---

source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs

Not sure what this project is about but I found the issue and thought I'd give it a try.

Increased day count

---

source/DasBlog.Services/ConfigFile/Interfaces/ISiteConfig.cs
source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Controllers/ActivityPubController.cs
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/Models/ActivityPubModels/Root.cs
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

Added support for [Webfinger](https://docs.joinmastodon.org/spec/webfinger). The blog owner gets to define the host email to validate against.

Support for webfinger

---

azure-pipelines.yml
source/DasBlog.Web.UI/Controllers/ActivityPubController.cs

Fixed the formatting of the webfinger response to remove the additional ampersand

Removed the additional ampersand.

---

source/DasBlog.Web.UI/Controllers/ActivityPubController.cs

Another mis-formatted piece of information.

Fixed the user url in the webfinger response.

---

source/DasBlog.Web.UI/Controllers/ActivityPubController.cs

Originally using the email as the subject, updated to using the mastadon account.

Fixed the subject

---

source/DasBlog.Web.UI/Controllers/ActivityPubController.cs

Hopefully get the format correct this time.

Reformat the subject ... again.

---

source/DasBlog.Services/ConfigFile/Interfaces/ISiteConfig.cs
source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Controllers/ActivityPubController.cs
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

This will not validate the full email address. Just looks at the domain

Removed references to Mastodon email. 

---

source/DasBlog.Web.UI/Controllers/ActivityPubController.cs

"wellknow" should have a dash in it.

---

source/DasBlog.Services/ConfigFile/Interfaces/ISiteConfig.cs
source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Tests/UnitTests/Config/site.config
source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Web.UI/Config/site.Development.config
source/DasBlog.Web.UI/Config/site.config
source/DasBlog.Web.UI/Controllers/BlogPostController.cs
source/DasBlog.Web.UI/DasBlog.Web.csproj
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

This is just a slightly enhanced version of https://github.com/poppastring/dasblog-core/pull/663 to support nofollow in referral links.

Support for Markdown in Comments

---

source/DasBlog.Web.UI/Controllers/ActivityPubController.cs

I did some checking and fixups for the config data that is used in the Webfinger implementation.

Webfinger cleanup

---

azure-pipelines.yml
source/DasBlog.Services/ConfigFile/Interfaces/ISiteConfig.cs
source/DasBlog.Services/ConfigFile/SiteConfig.cs
source/DasBlog.Tests/UnitTests/SiteConfigTest.cs
source/DasBlog.Web.Repositories/BlogManager.cs
source/DasBlog.Web.Repositories/Interfaces/IBlogManager.cs
source/DasBlog.Web.UI/Controllers/AdminController.cs
source/DasBlog.Web.UI/Controllers/HomeController.cs
source/DasBlog.Web.UI/Models/AdminViewModels/BlogPostListViewModel.cs
source/DasBlog.Web.UI/Models/AdminViewModels/DasBlogSettingsViewModel.cs
source/DasBlog.Web.UI/Models/AdminViewModels/SiteViewModel.cs
source/DasBlog.Web.UI/Views/Admin/Settings.cshtml

Allows you to pin a single post to the home page for a more static entry point in the site. Does not impact your RSS feed.

Pin to home

---

source/DasBlog.Tests/UnitTests/UI/StringExtensionTest.cs
source/DasBlog.Web.Core/Extensions/StringExtensions.cs
source/DasBlog.Web.UI/Mappers/ProfilePost.cs

This contribution was inspired by Copilot.

Support defining a hero image in the post

---

source/DasBlog.CLI/dasblog-core.runtimeconfig.json

Update the runtime config file

---

source/DasBlog.Web.UI/DasBlog.Web.csproj

Removes a bunch of folders associated with language support.

Removed satellite resource language folders

---

source/DasBlog.Tests/UnitTests/Extensions/StringExtensionTest.cs
source/DasBlog.Tests/UnitTests/ExtensionsConfig/StringExtensionTest.cs
source/DasBlog.Tests/UnitTests/Settings/DasBlogSettingsTests.cs
source/DasBlog.Tests/UnitTests/UI/StringExtensionTest.cs
source/DasBlog.Web.Core/Extensions/StringExtensions.cs

Improved test coverage and refactored test structure for better maintainability and robustness.  
This pull request adds comprehensive unit tests for `StringExtension` methods and the `DasBlogSettings` class, refactors test organization, and enhances test coverage for edge cases.  
- **`StringExtensionTest.cs`**: Added extensive unit tests for string manipulation methods and moved the class to a new namespace (`DasBlog.Tests.UnitTests.Extensions`).  
- **`DasBlogSettingsTests.cs`**: Introduced a new test class with mocking for dependencies and added tests for URL generation, time zone adjustments, and admin validation.  
- Removed the old, less comprehensive implementation of `StringExtensionTest` from `DasBlog.Tests.UnitTests.Misc`.  
- Enhanced test coverage for edge cases, including …

Unit tests for DasBlogSettings
